---
# yamllint disable rule:line-length
# ------------------------------------------------------------------
# Global settings
# ------------------------------------------------------------------

image: "adorsys/ci-build:201907"

# ------------------------------------------------------------------
# stages
# ------------------------------------------------------------------

stages:
  - "Lint"
  - "Compile" # build jar and provide as artifact
  - "Test"    # run tests and code quality checks
  - "Package" # dockerize jar and push to docker registry
  - "Deploy"  # push to openshift registry (snapshot deployment) or release registry

# ------------------------------------------------------------------
# variables
# ------------------------------------------------------------------

variables:
  SONAR_HOST: "https://psd2-quality.cloud.adorsys.de"

  DOCKER_IMAGE_NAME_CNT_MGMNT: "xs2a-consent-management"
  DOCKER_IMAGE_NAME_ASPSP_PROFILE: "xs2a-aspsp-profile"
  DOCKER_IMAGE_NAME_XS2A: "xs2a-service"

  ###########################
  # Public Dockerhub Images #
  ###########################

  DOCKERHUB_REGISTRY: "docker.io"

  DOCKERHUB_NAMESPACE: "adorsys"

  ############################
  # Private Openshift Images #
  ############################

  OPENSHIFT_NAMESPACE_SUPPORT: "multibanking-xs2a"
  OPENSHIFT_NAMESPACE_SUPPORT4X: "adorsys-psd2-support4x"
  OPENSHIFT_NAMESPACE_DEV: "adorsys-psd2-develop"
  OPENSHIFT_NAMESPACE_INTEG: "adorsys-psd2-integ"
  OPENSHIFT_NAMESPACE_DEMO: "adorsys-psd2-demo"

  ###########################
  # Build variables         #
  ###########################

  JAVA_TOOL_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAM=3G -XX:MaxRAMFraction=3"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# ------------------------------------------------------------------
# reusable yaml anchors
# ------------------------------------------------------------------

.build_java: &build_java
  script:
    - jabba use ${JAVA_VERSION}
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - env BUILD_NUMBER=$CI_PIPELINE_IID ./scripts/set_xs2a_connector_version_in_swagger.sh
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp -DskipTests -DskipITs -Dci.build.number=Build\:${CI_PIPELINE_ID} clean install

.java_tests: &java_tests
  script:
    - jabba use $JAVA_VERSION
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp -DskipITs --fail-at-end clean install

# Build docker images and push them to Dockerhub (depending on ${DOCKER_TAG})
.build_dockerhub_image: &build_dockerhub_image
  script:
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_CNT_MGMNT}:${DOCKER_TAG}" consent-management/cms-standalone-service
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_ASPSP_PROFILE}:${DOCKER_TAG}" aspsp-profile/aspsp-profile-server
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A}:${DOCKER_TAG}" xs2a-standalone-starter

    - docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_PASS}
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_CNT_MGMNT}:${DOCKER_TAG}"
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_ASPSP_PROFILE}:${DOCKER_TAG}"
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A}:${DOCKER_TAG}"
    - docker logout

# Copy Dockerhub images to Openshift (depending on ${DOCKER_TAG} and ${OPENSHIFT_NAMESPACE})
.deploy_openshift: &deploy_openshift
  script:
    - >-
      skopeo copy
      --dest-creds=openshift:${OPENSHIFT_TOKEN}
      "docker://${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_CNT_MGMNT}:${DOCKER_TAG}"
      "docker://${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/${DOCKER_IMAGE_NAME_CNT_MGMNT}:latest"
    - >-
      skopeo copy
      --dest-creds=openshift:${OPENSHIFT_TOKEN}
      "docker://${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_ASPSP_PROFILE}:${DOCKER_TAG}"
      "docker://${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/${DOCKER_IMAGE_NAME_ASPSP_PROFILE}:latest"

# ------------------------------------------------------------------
# jobs
# ------------------------------------------------------------------

#-------------------------------------------------------------------
# lint
#-------------------------------------------------------------------

Lint:Docker_compose:
  image: maven:3.6-jdk-8-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt update && apt install yamllint docker-compose make -yq
    - echo "Run Docker compose lint"
    - docker-compose -f docker-compose.yml config  -q

Lint:Ci_file:
  image: debian:stretch-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt-get update && apt-get install yamllint python3-pkg-resources -yq
    - echo "Run Gitlab ci file lint"
    - yamllint -d relaxed .gitlab-ci.yml

Lint:XS2A_core_yaml_json_xml:
  image: debian:stretch-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt-get update && apt-get install jsonlint yamllint libxml2-utils make curl -yq && ln -s /usr/bin/jsonlint-php /usr/bin/jsonlint
    - curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    - echo "Run Xs2a core lint"
    - find ./ -type f -name "*.json" -exec jsonlint -q {} \; # lint all json
# commented cause get many small errors for yaml with spaces empty lines and etc
#    - find ./ -type f \( -name "*.yml" -o -name "*.yaml" \) -exec yamllint -d "{extends: relaxed, rules: {line-length: {max: 160}}}" {} \;
# commented cause get error Unsupported version '1.1'
	  - find ./ -type f \( -iname "*.xml" ! -iname pom.xml \) -exec xmllint --noout {} \; # lint all xml

Lint:XS2A_core_dockerfiles:
  image: debian:stretch-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt-get update && apt-get install jsonlint yamllint libxml2-utils make curl -yq && ln -s /usr/bin/jsonlint-php /usr/bin/jsonlint
    - curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    - echo "Run Xs2a core dockerfile check"
    - docker run --rm -i hadolint/hadolint < ./consent-management/cms-standalone-service/Dockerfile
    - docker run --rm -i hadolint/hadolint < ./aspsp-profile/aspsp-profile-server/Dockerfile
    - docker run --rm -i hadolint/hadolint < ./xs2a-standalone-starter/Dockerfile
    - - docker run --rm -i hadolint/hadolint < ./certificate-generator/Dockerfile

Lint:PMD_CPD_Report:
  image: maven:3.6-jdk-8-slim
  stage: "Lint"
  cache: {}
  except:
    - schedules
    - develop
    - master
  script:
#    - jabba use ${JAVA_VERSION}
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp -Dmaven.test.skip=true package pmd:pmd pmd:cpd
  variables:
    JAVA_VERSION: "system@1.8"
  artifacts:
    paths:
    - "qa/pmd/pmd-ruleset.xml"
    - "**/**/*/pmd.html"
    - "**/*/pmd.xml"
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF_NAME#*v}-pmd"
    expire_in: "10 day"


Lint:PMD_Check_Java11:
  image: maven:3.6-jdk-11-slim
  stage: "Lint"
  cache: {}
  except:
    - schedules
    - develop
    - master
  variables:
    JAVA_VERSION: "system@1.11"
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
  script:
#    - jabba use ${JAVA_VERSION}
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp -Dmaven.test.skip=true package pmd:pmd pmd:cpd

#-------------------------------------------------------------------
# Build
#-------------------------------------------------------------------

Build:XS2A_Java8:
  stage: "Compile"
  variables:
    JAVA_VERSION: "system@1.8"
  <<: *build_java
  artifacts:
    paths:
      - "**/target/*"
      - "**/**/target/*"
      - ".m2/repository/de/adorsys/psd2/*/*"
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF_NAME#*v}"
    expire_in: "10 day"

Build:XS2A_Java11:
  stage: "Compile"
  variables:
    JAVA_VERSION: "system@1.11"
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
  <<: *build_java
  artifacts:
    paths:
      - "xs2a-standalone-starter/target/xs2a-standalone-starter-exec.jar"
      - "consent-management/cms-standalone-service/target/consent-management*jar"
      - "aspsp-profile/aspsp-profile-server/target/aspsp-profile*jar"
      - "**/target/*"
      - "**/**/target/*"
      - ".m2/repository/de/adorsys/psd2/*/*"
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF_NAME#*v}"
    expire_in: "1 day"

#-------------------
# Integration tests (IT)
#-------------------

ITtests:XS2A_Java8:
  image: maven:3.6-jdk-8-slim
  stage: "Test"
  dependencies:
    - "Build:XS2A_Java8"
  script:
#    - jabba use ${JAVA_VERSION}
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp failsafe:integration-test
  variables:
    JAVA_VERSION: "system@1.8"

ITtests:XS2A_Java11:
  image: maven:3.6-jdk-11-slim
  stage: "Test"
  dependencies:
    - "Build:XS2A_Java11"
  script:
#    - jabba use ${JAVA_VERSION}
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp failsafe:integration-test
  variables:
    JAVA_VERSION: "system@1.11"
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"


DOCKER test image build:
  stage: "Test"
  script:
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_CNT_MGMNT}:${DOCKER_TAG}" consent-management/cms-standalone-service
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_ASPSP_PROFILE}:${DOCKER_TAG}" aspsp-profile/aspsp-profile-server
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A}:${DOCKER_TAG}" xs2a-standalone-starter
  variables:
    DOCKER_TAG: develop
  except:
    - master-2.x
    - support-2.x

PMD Check Java8:
  stage: "Test"
  variables:
    JAVA_VERSION: "system@1.8"
  script:
    - jabba use ${JAVA_VERSION}
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -Dmaven.test.skip=true package pmd:check

Doc Check Java8:
  stage: "Test"
  variables:
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
    JAVA_VERSION: "system@1.8"
  script:
    - jabba use ${JAVA_VERSION}
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -Dmaven.test.skip=true -Pjavadoc verify javadoc:javadoc
  artifacts:
    paths:
    - "**/target/site/*"
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF_NAME#*v}-javadoc"
    expire_in: "10 day"

Doc Check Java11:
  stage: "Test"
  variables:
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
    JAVA_VERSION: "system@1.11"
  script:
    - jabba use ${JAVA_VERSION}
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -Dmaven.test.skip=true -Pjavadoc verify javadoc:javadoc

Unit Tests Java8:
  stage: "Test"
  <<: *java_tests
  variables:
    JAVA_VERSION: "system@1.8"
  artifacts:
    paths:
    - "**/target/surefire-reports/*"
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF_NAME#*v}-*"
    expire_in: "10 day"

Unit Tests Java11:
  stage: "Test"
  <<: *java_tests
  variables:
    JAVA_VERSION: "system@1.11"
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"

Sonarcube Tests:
  stage: "Test"
  only:
    - develop
  script:
    - jabba use system@1.8
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn --fail-at-end clean install
    - mvn sonar:sonar -Dsonar.host.url=${SONAR_HOST} -Dsonar.login=${SONAR_TOKEN}

AsciiDoc Test:
  stage: "Test"
  image: adorsys/arc42-tools
  variables:
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
  script:
    - make pages

# Build DEVELOP image and deploy to DEV

Push to DockerHub (develop):
  stage: "Package"
  only:
    - develop
  variables:
    DOCKER_TAG: develop
  <<: *build_dockerhub_image

Deploy to Openshift (develop):
  stage: "Deploy"
  cache: {}
  dependencies: []
  only:
    - develop
  variables:
    GIT_STRATEGY: none
    DOCKER_TAG: develop # Dockerhub source tag
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_DEV} # Openshift target namespace
  <<: *deploy_openshift

# Build SUPPORT image and deploy to SUPPORT

Push to DockerHub (support):
  stage: "Package"
  only:
    - support-2.x
  script:
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A}:support" xs2a-standalone-starter
    - docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_PASS}
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A}:support"
    - docker logout

Deploy to Openshift (support):
  stage: "Deploy"
  only:
    - support-2.x
  script:
    - >-
      skopeo copy
      --dest-creds=openshift:${OPENSHIFT_TOKEN}
      "docker://${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A}:support"
      "docker://${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE_SUPPORT}/${DOCKER_IMAGE_NAME_XS2A}:latest"
    - >-
      skopeo copy
      --dest-creds=openshift:${OPENSHIFT_TOKEN}
      "docker://${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_CNT_MGMNT}:support"
      "docker://${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE_SUPPORT}/${DOCKER_IMAGE_NAME_CNT_MGMNT}:latest"
    - >-
      skopeo copy
      --dest-creds=openshift:${OPENSHIFT_TOKEN}
      "docker://${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_ASPSP_PROFILE}:support"
      "docker://${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE_SUPPORT}/${DOCKER_IMAGE_NAME_ASPSP_PROFILE}:latest"

#Build Support-4.x imnages and deploy to support-4.x

Push to DockerHub (support-4.x):
  stage: "Package"
  only:
    - support-4.x
  variables:
    DOCKER_TAG: support4x
  <<: *build_dockerhub_image

Deploy to Openshift (support-4.x):
  stage: "Deploy"
  cache: {}
  dependencies: []
  only:
    - support-4.x
  variables:
    GIT_STRATEGY: none
    DOCKER_TAG: support4x # Dockerhub source tag
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_SUPPORT4X} # Openshift target namespace
  <<: *deploy_openshift

# Build NIGHTLY image and deploy (scheduled) to INTEG

Push to DockerHub (nightly):
  stage: "Package"
  only:
    - schedules
  variables:
    DOCKER_TAG: nightly
  <<: *build_dockerhub_image

Deploy to Openshift (nightly):
  stage: "Deploy"
  cache: {}
  dependencies: []
  only:
  - schedules
  variables:
    GIT_STRATEGY: none
    DOCKER_TAG: nightly # Dockerhub source tag
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_INTEG} # Openshift target namespace
  <<: *deploy_openshift

# Build MASTER image and deploy to DEMO

Push to DockerHub (master):
  stage: "Package"
  only:
    - master
  variables:
    DOCKER_TAG: latest
  <<: *build_dockerhub_image

Deploy to Openshift (master):
  stage: "Deploy"
  cache: {}
  dependencies: []
  only:
    - master
  variables:
    GIT_STRATEGY: none
    DOCKER_TAG: latest # Dockerhub source tag
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_DEMO} # Openshift target namespace
  <<: *deploy_openshift

# Build RELEASE image and deploy (manual) to DEMO

Push to DockerHub (release):
  stage: "Package"
  only:
    - tags
  variables:
    DOCKER_TAG: ${CI_COMMIT_TAG}
  <<: *build_dockerhub_image

Deploy to Openshift (release):
  stage: "Deploy"
  cache: {}
  dependencies: []
  only:
    - tags
  when: manual
  variables:
    GIT_STRATEGY: none
    DOCKER_TAG: $CI_COMMIT_TAG # Dockerhub source tag
    OPENSHIFT_NAMESPACE: ${OPENSHIFT_NAMESPACE_DEMO} # Openshift target namespace
  <<: *deploy_openshift
